//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.32559.
// 
#pragma warning disable 1591

namespace HLP.Comum.WebServices.wsHLPServicos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IServices", Namespace="http://tempuri.org/")]
    public partial class Services : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SetLogErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVersoesMagnificusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Services() {
            this.Url = global::HLP.Comum.WebServices.Properties.Settings.Default.HLP_Comum_WebServices_wsHLPServicos_Services;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SetLogErrorCompletedEventHandler SetLogErrorCompleted;
        
        /// <remarks/>
        public event GetVersoesMagnificusCompletedEventHandler GetVersoesMagnificusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServices/SetLogError", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetLogError([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Log log, out bool SetLogErrorResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SetLogErrorResultSpecified) {
            object[] results = this.Invoke("SetLogError", new object[] {
                        log});
            SetLogErrorResult = ((bool)(results[0]));
            SetLogErrorResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void SetLogErrorAsync(Log log) {
            this.SetLogErrorAsync(log, null);
        }
        
        /// <remarks/>
        public void SetLogErrorAsync(Log log, object userState) {
            if ((this.SetLogErrorOperationCompleted == null)) {
                this.SetLogErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetLogErrorOperationCompleted);
            }
            this.InvokeAsync("SetLogError", new object[] {
                        log}, this.SetLogErrorOperationCompleted, userState);
        }
        
        private void OnSetLogErrorOperationCompleted(object arg) {
            if ((this.SetLogErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetLogErrorCompleted(this, new SetLogErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServices/GetVersoesMagnificus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://hlp.com.br/WebServices/log")]
        public VersoesModel[] GetVersoesMagnificus() {
            object[] results = this.Invoke("GetVersoesMagnificus", new object[0]);
            return ((VersoesModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVersoesMagnificusAsync() {
            this.GetVersoesMagnificusAsync(null);
        }
        
        /// <remarks/>
        public void GetVersoesMagnificusAsync(object userState) {
            if ((this.GetVersoesMagnificusOperationCompleted == null)) {
                this.GetVersoesMagnificusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVersoesMagnificusOperationCompleted);
            }
            this.InvokeAsync("GetVersoesMagnificus", new object[0], this.GetVersoesMagnificusOperationCompleted, userState);
        }
        
        private void OnGetVersoesMagnificusOperationCompleted(object arg) {
            if ((this.GetVersoesMagnificusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVersoesMagnificusCompleted(this, new GetVersoesMagnificusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.32559")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hlp.com.br/WebServices/log")]
    public partial class Log {
        
        private string xEmpresaField;
        
        private string xFormularioField;
        
        private string xAcaoField;
        
        private string xMessageField;
        
        private string xInnerField;
        
        private string xDetalhesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xEmpresa {
            get {
                return this.xEmpresaField;
            }
            set {
                this.xEmpresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xFormulario {
            get {
                return this.xFormularioField;
            }
            set {
                this.xFormularioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xAcao {
            get {
                return this.xAcaoField;
            }
            set {
                this.xAcaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xMessage {
            get {
                return this.xMessageField;
            }
            set {
                this.xMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xInner {
            get {
                return this.xInnerField;
            }
            set {
                this.xInnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xDetalhes {
            get {
                return this.xDetalhesField;
            }
            set {
                this.xDetalhesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.32559")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://hlp.com.br/WebServices/log")]
    public partial class VersoesModel {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    public delegate void SetLogErrorCompletedEventHandler(object sender, SetLogErrorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetLogErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetLogErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool SetLogErrorResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool SetLogErrorResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    public delegate void GetVersoesMagnificusCompletedEventHandler(object sender, GetVersoesMagnificusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.32559")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVersoesMagnificusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVersoesMagnificusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VersoesModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VersoesModel[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591