//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Comum.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Arquivos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Arquivos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HLP.Comum.Messages.Arquivos", typeof(Arquivos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\EstruturaRelatorios.xml.
        /// </summary>
        public static string Estrutura_Relatorio {
            get {
                return ResourceManager.GetString("Estrutura_Relatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarraStatus.xml.
        /// </summary>
        public static string ISOLATED_BarraStatus {
            get {
                return ResourceManager.GetString("ISOLATED_BarraStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseConfig.xml.
        /// </summary>
        public static string ISOLATED_BaseConfig {
            get {
                return ResourceManager.GetString("ISOLATED_BaseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BotoesLaterais.xml.
        /// </summary>
        public static string ISOLATED_BotoesLaterais {
            get {
                return ResourceManager.GetString("ISOLATED_BotoesLaterais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoritos.xml.
        /// </summary>
        public static string ISOLATED_Favoritos {
            get {
                return ResourceManager.GetString("ISOLATED_Favoritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembretes.xml.
        /// </summary>
        public static string ISOLATED_Lembretes {
            get {
                return ResourceManager.GetString("ISOLATED_Lembretes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuPrincipal.xml.
        /// </summary>
        public static string ISOLATED_Menu {
            get {
                return ResourceManager.GetString("ISOLATED_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualSistema.xml.
        /// </summary>
        public static string ISOLATED_Visual {
            get {
                return ResourceManager.GetString("ISOLATED_Visual", resourceCulture);
            }
        }
    }
}
