//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Comum.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HLP.Comum.Messages.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja Confirmar a Alteração do Registro?.
        /// </summary>
        public static string Alterar {
            get {
                return ResourceManager.GetString("Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao Tentar Converter Texto para Numérico. Verifique se não há Letras nos Campos da Tela.
        /// </summary>
        public static string CampoTxt_Num {
            get {
                return ResourceManager.GetString("CampoTxt_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os Campos em Alerta são Obrigatórios para o Registro ou estão Incorretos!.
        /// </summary>
        public static string CampoVazio_Incorreto {
            get {
                return ResourceManager.GetString("CampoVazio_Incorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja Cancelar o Registro?.
        /// </summary>
        public static string CCancelar {
            get {
                return ResourceManager.GetString("CCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja Realmente Sair?.
        /// </summary>
        public static string DesejaSair {
            get {
                return ResourceManager.GetString("DesejaSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma Exceção ao Manipular essa Ação : {0}{0}Verifique a Mensagem abaixo: {0}________________________________{0}{0}.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja Confirmar a Exclusão do Registro?.
        /// </summary>
        public static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja visualizar Lista de Relatórios?.
        /// </summary>
        public static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        public static string MSG_Alerta {
            get {
                return ResourceManager.GetString("MSG_Alerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        public static string MSG_Aviso {
            get {
                return ResourceManager.GetString("MSG_Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        public static string MSG_Confirmacao {
            get {
                return ResourceManager.GetString("MSG_Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string MSG_Erro {
            get {
                return ResourceManager.GetString("MSG_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja Confirmar a Gravação do Registro?.
        /// </summary>
        public static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Númer do CNPJ é Inválido !.
        /// </summary>
        public static string Validacao_CNPJ {
            get {
                return ResourceManager.GetString("Validacao_CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número do CPF Inválido!.
        /// </summary>
        public static string Validacao_CPF {
            get {
                return ResourceManager.GetString("Validacao_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo é obrigatório.
        /// </summary>
        public static string Validacao_EmBranco {
            get {
                return ResourceManager.GetString("Validacao_EmBranco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Inválido, Campo Numérico Inteiro !.
        /// </summary>
        public static string Validacao_Inteiro {
            get {
                return ResourceManager.GetString("Validacao_Inteiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Incompleto !.
        /// </summary>
        public static string Validacao_Outros {
            get {
                return ResourceManager.GetString("Validacao_Outros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Telefone  Inválido !.
        /// </summary>
        public static string Validacao_Tel {
            get {
                return ResourceManager.GetString("Validacao_Tel", resourceCulture);
            }
        }
    }
}
