//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Comum.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pastas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pastas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HLP.Comum.Messages.Pastas", typeof(Pastas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \configuracoes\Reports\Estrutura\.
        /// </summary>
        public static string Estrutura_Relatorios {
            get {
                return ResourceManager.GetString("Estrutura_Relatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \configuracoes\Reports\Filtros\.
        /// </summary>
        public static string Filtros_Relatorios {
            get {
                return ResourceManager.GetString("Filtros_Relatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Imagens\.
        /// </summary>
        public static string Imagens {
            get {
                return ResourceManager.GetString("Imagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \configuracoes\Modulos\.
        /// </summary>
        public static string Modulos {
            get {
                return ResourceManager.GetString("Modulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Relatorios\.
        /// </summary>
        public static string Relatorios {
            get {
                return ResourceManager.GetString("Relatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \configuracoes\Telas\.
        /// </summary>
        public static string Telas {
            get {
                return ResourceManager.GetString("Telas", resourceCulture);
            }
        }
    }
}
