//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLP.Comum.Ws.servicoHlp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Log", Namespace="http://hlp.com.br/WebServices/log")]
    [System.SerializableAttribute()]
    public partial class Log : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xFormularioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xAcaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xInnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xDetalhesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xEmpresa {
            get {
                return this.xEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.xEmpresaField, value) != true)) {
                    this.xEmpresaField = value;
                    this.RaisePropertyChanged("xEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xFormulario {
            get {
                return this.xFormularioField;
            }
            set {
                if ((object.ReferenceEquals(this.xFormularioField, value) != true)) {
                    this.xFormularioField = value;
                    this.RaisePropertyChanged("xFormulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string xAcao {
            get {
                return this.xAcaoField;
            }
            set {
                if ((object.ReferenceEquals(this.xAcaoField, value) != true)) {
                    this.xAcaoField = value;
                    this.RaisePropertyChanged("xAcao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string xMessage {
            get {
                return this.xMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.xMessageField, value) != true)) {
                    this.xMessageField = value;
                    this.RaisePropertyChanged("xMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string xInner {
            get {
                return this.xInnerField;
            }
            set {
                if ((object.ReferenceEquals(this.xInnerField, value) != true)) {
                    this.xInnerField = value;
                    this.RaisePropertyChanged("xInner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string xDetalhes {
            get {
                return this.xDetalhesField;
            }
            set {
                if ((object.ReferenceEquals(this.xDetalhesField, value) != true)) {
                    this.xDetalhesField = value;
                    this.RaisePropertyChanged("xDetalhes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VersoesModel", Namespace="http://hlp.com.br/WebServices/VersoesModel")]
    [System.SerializableAttribute()]
    public partial class VersoesModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dtArquivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xCaminhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xVersaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dtArquivo {
            get {
                return this.dtArquivoField;
            }
            set {
                if ((object.ReferenceEquals(this.dtArquivoField, value) != true)) {
                    this.dtArquivoField = value;
                    this.RaisePropertyChanged("dtArquivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xCaminho {
            get {
                return this.xCaminhoField;
            }
            set {
                if ((object.ReferenceEquals(this.xCaminhoField, value) != true)) {
                    this.xCaminhoField = value;
                    this.RaisePropertyChanged("xCaminho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xVersao {
            get {
                return this.xVersaoField;
            }
            set {
                if ((object.ReferenceEquals(this.xVersaoField, value) != true)) {
                    this.xVersaoField = value;
                    this.RaisePropertyChanged("xVersao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="servicoHlp.IServices")]
    public interface IServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/SetLogError", ReplyAction="http://tempuri.org/IServices/SetLogErrorResponse")]
        bool SetLogError(HLP.Comum.Ws.servicoHlp.Log log);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/SetLogError", ReplyAction="http://tempuri.org/IServices/SetLogErrorResponse")]
        System.Threading.Tasks.Task<bool> SetLogErrorAsync(HLP.Comum.Ws.servicoHlp.Log log);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetVersoesMagnificus", ReplyAction="http://tempuri.org/IServices/GetVersoesMagnificusResponse")]
        HLP.Comum.Ws.servicoHlp.VersoesModel[] GetVersoesMagnificus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetVersoesMagnificus", ReplyAction="http://tempuri.org/IServices/GetVersoesMagnificusResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Ws.servicoHlp.VersoesModel[]> GetVersoesMagnificusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DownloadFile", ReplyAction="http://tempuri.org/IServices/DownloadFileResponse")]
        byte[] DownloadFile(string xVersao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DownloadFile", ReplyAction="http://tempuri.org/IServices/DownloadFileResponse")]
        System.Threading.Tasks.Task<byte[]> DownloadFileAsync(string xVersao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetUltimaVersao", ReplyAction="http://tempuri.org/IServices/GetUltimaVersaoResponse")]
        string GetUltimaVersao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetUltimaVersao", ReplyAction="http://tempuri.org/IServices/GetUltimaVersaoResponse")]
        System.Threading.Tasks.Task<string> GetUltimaVersaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetUltimosScripts", ReplyAction="http://tempuri.org/IServices/GetUltimosScriptsResponse")]
        HLP.Comum.Ws.servicoHlp.VersoesModel[] GetUltimosScripts(string xVersao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetUltimosScripts", ReplyAction="http://tempuri.org/IServices/GetUltimosScriptsResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Ws.servicoHlp.VersoesModel[]> GetUltimosScriptsAsync(string xVersao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetScripts", ReplyAction="http://tempuri.org/IServices/GetScriptsResponse")]
        HLP.Comum.Ws.servicoHlp.VersoesModel[] GetScripts(string xVersao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetScripts", ReplyAction="http://tempuri.org/IServices/GetScriptsResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Ws.servicoHlp.VersoesModel[]> GetScriptsAsync(string xVersao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DownloadScript", ReplyAction="http://tempuri.org/IServices/DownloadScriptResponse")]
        byte[] DownloadScript(string xVersao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DownloadScript", ReplyAction="http://tempuri.org/IServices/DownloadScriptResponse")]
        System.Threading.Tasks.Task<byte[]> DownloadScriptAsync(string xVersao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetScriptVersaoExe", ReplyAction="http://tempuri.org/IServices/GetScriptVersaoExeResponse")]
        HLP.Comum.Ws.servicoHlp.VersoesModel[] GetScriptVersaoExe(string xVersao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetScriptVersaoExe", ReplyAction="http://tempuri.org/IServices/GetScriptVersaoExeResponse")]
        System.Threading.Tasks.Task<HLP.Comum.Ws.servicoHlp.VersoesModel[]> GetScriptVersaoExeAsync(string xVersao);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesChannel : HLP.Comum.Ws.servicoHlp.IServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesClient : System.ServiceModel.ClientBase<HLP.Comum.Ws.servicoHlp.IServices>, HLP.Comum.Ws.servicoHlp.IServices {
        
        public ServicesClient() {
        }
        
        public ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SetLogError(HLP.Comum.Ws.servicoHlp.Log log) {
            return base.Channel.SetLogError(log);
        }
        
        public System.Threading.Tasks.Task<bool> SetLogErrorAsync(HLP.Comum.Ws.servicoHlp.Log log) {
            return base.Channel.SetLogErrorAsync(log);
        }
        
        public HLP.Comum.Ws.servicoHlp.VersoesModel[] GetVersoesMagnificus() {
            return base.Channel.GetVersoesMagnificus();
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Ws.servicoHlp.VersoesModel[]> GetVersoesMagnificusAsync() {
            return base.Channel.GetVersoesMagnificusAsync();
        }
        
        public byte[] DownloadFile(string xVersao) {
            return base.Channel.DownloadFile(xVersao);
        }
        
        public System.Threading.Tasks.Task<byte[]> DownloadFileAsync(string xVersao) {
            return base.Channel.DownloadFileAsync(xVersao);
        }
        
        public string GetUltimaVersao() {
            return base.Channel.GetUltimaVersao();
        }
        
        public System.Threading.Tasks.Task<string> GetUltimaVersaoAsync() {
            return base.Channel.GetUltimaVersaoAsync();
        }
        
        public HLP.Comum.Ws.servicoHlp.VersoesModel[] GetUltimosScripts(string xVersao) {
            return base.Channel.GetUltimosScripts(xVersao);
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Ws.servicoHlp.VersoesModel[]> GetUltimosScriptsAsync(string xVersao) {
            return base.Channel.GetUltimosScriptsAsync(xVersao);
        }
        
        public HLP.Comum.Ws.servicoHlp.VersoesModel[] GetScripts(string xVersao) {
            return base.Channel.GetScripts(xVersao);
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Ws.servicoHlp.VersoesModel[]> GetScriptsAsync(string xVersao) {
            return base.Channel.GetScriptsAsync(xVersao);
        }
        
        public byte[] DownloadScript(string xVersao) {
            return base.Channel.DownloadScript(xVersao);
        }
        
        public System.Threading.Tasks.Task<byte[]> DownloadScriptAsync(string xVersao) {
            return base.Channel.DownloadScriptAsync(xVersao);
        }
        
        public HLP.Comum.Ws.servicoHlp.VersoesModel[] GetScriptVersaoExe(string xVersao) {
            return base.Channel.GetScriptVersaoExe(xVersao);
        }
        
        public System.Threading.Tasks.Task<HLP.Comum.Ws.servicoHlp.VersoesModel[]> GetScriptVersaoExeAsync(string xVersao) {
            return base.Channel.GetScriptVersaoExeAsync(xVersao);
        }
    }
}
